spring:
  data:
    mongodb:
#      host: 192.168.48.132
#      database: test
      uri: mongodb://test:******@192.168.48.132:27017/test
#      port: 27017
#      username: huangbaoning
#      password: 666151
server:
  port: 8888