spring:
  data:
    mongodb:
#      host: 192.168.48.132
#      database: test
      uri: mongodb://test:******@192.168.48.132:27017/test
#      port: 27017
#      username: test
#      password: ******
server:
  port: 8888

logging:
  level:
    root: info

